### ISSUE TITLE
Docs?

### ISSUE THREAD

**Issue by TheDayIsMyEnemy** [desech/desech-studio#1]
Are there any docs available

**Comment by cata-code** [comment]
Hey @TheDayIsMyEnemy 

If you check the [last commit](https://github.com/desech/desech-studio/commit/3cc39148ecca3a73b3c6d2a1f916e0112a331635) you can see the internal docs that were used to execute/build the software. Unfortunately there are no proper docs for the code framework.

**Comment by TheDayIsMyEnemy** [comment]
Okay, thanks
